In [34]:
#conda install numpy

In [35]:
import numpy as np

In [36]:
#Numpy Arrays
my_list = [1,2,3]

In [37]:
nparr = np.array(my_list)

In [38]:
nparr

array([1, 2, 3])

In [39]:
#two dimentional 
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [40]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
#arange
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [43]:
#zeros and ones
np.zeros(4)

array([0., 0., 0., 0.])

In [44]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
np.ones(4)

array([1., 1., 1., 1.])

In [46]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
#linspace
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [48]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [49]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [50]:
#eye
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [51]:
#Random
# uniform distribution
np.random.rand(2)

array([0.01793834, 0.73282112])

In [52]:
#standard normal distribution
np.random.randn(2)

array([-0.68563295,  0.83228852])

In [53]:
#standard normal distribution
np.random.randn(5,5)

array([[-1.13386143,  0.57190019, -0.2483786 ,  0.33031765,  0.47178116],
       [-0.58112402,  0.81302426,  1.10169038, -0.82646329,  0.46328424],
       [ 1.91963586,  1.65303206, -0.10774729, -1.30803789,  1.19735496],
       [-1.49021961, -0.29695223,  0.20875357,  0.14159302,  0.61153041],
       [-2.06267013, -0.97936057, -1.71352677,  1.657483  , -0.44160264]])

In [54]:
np.random.randint(1,100)

4

In [55]:
np.random.randint(1,100,13)

array([75, 43, 78, 70, 81, 73, 71, 12, 94, 25, 39, 50, 44])

In [56]:
arr = np.arange(25)

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [58]:
#Reshape: changes dimension of an array
arr.reshape(4,6)

ValueError: cannot reshape array of size 25 into shape (4,6)

In [60]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
ranarr = np.random.randint(0,50,10)

In [62]:
ranarr.max()

49

In [63]:
ranarr

array([49,  9,  5, 17, 38, 43, 11, 31,  2,  4])

In [64]:
ranarr.argmax()

0

In [65]:
ranarr[0]

49

In [66]:
ranarr.min()

2

In [67]:
ranarr.argmin()

8

In [68]:
ranarr.shape

(10,)

In [69]:
arr2 = arr.reshape(5,5)

In [70]:
arr2.shape

(5, 5)

In [71]:
arr2.dtype

dtype('int32')

In [72]:
#indexing and selection
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [73]:
#value at specific position
arr[8]

8

In [74]:
#get values in range
arr[1:5]

array([1, 2, 3, 4])

In [75]:
arr[9:]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [76]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [77]:
#Broadcasting
arr[0:5] = 500
arr

array([500, 500, 500, 500, 500,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [78]:
slice_of_Array = arr[4:9]
slice_of_Array

array([500,   5,   6,   7,   8])

In [79]:
slice_of_Array[:] = 900

In [80]:
slice_of_Array

array([900, 900, 900, 900, 900])

In [81]:
arr

array([500, 500, 500, 500, 900, 900, 900, 900, 900,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [82]:
#copy
arr_copy = arr.copy()

In [83]:
arr_copy

array([500, 500, 500, 500, 900, 900, 900, 900, 900,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [84]:
arr_copy[:] = 765

In [85]:
arr_copy

array([765, 765, 765, 765, 765, 765, 765, 765, 765, 765, 765, 765, 765,
       765, 765, 765, 765, 765, 765, 765, 765, 765, 765, 765, 765])

In [86]:
arr

array([500, 500, 500, 500, 900, 900, 900, 900, 900,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [87]:
arr2d = np.array([[5,10,15],[20,25,30],[40,45,50]])

In [88]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [40, 45, 50]])

In [89]:
arr2d[1]

array([20, 25, 30])

In [90]:
arr2d[1][1]

25

In [91]:
#same result different syntax
arr2d[1,1]

25

In [92]:
arr2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [93]:
arr2d[0:2,1:3]

array([[10, 15],
       [25, 30]])

In [94]:
arr2d[0:2,1:2]

array([[10],
       [25]])

In [95]:
#selection
arr = np.arange(1,11)

In [96]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [98]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [99]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
#operations
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [102]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [103]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [104]:
newarr = np.arange(0,10)

In [105]:
newarr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
newarr / newarr

<ipython-input-106-056b266ea0b0>:1: RuntimeWarning: invalid value encountered in true_divide
  newarr / newarr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [107]:
1/0

ZeroDivisionError: division by zero

In [ ]:
#universal functions
np.sqrt(arr)

In [ ]:
np.max(arr)

In [ ]:
np.sin(arr)

In [ ]:
#get common items between two arrays (numpy)
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([2,4,6,8,10,12,14,16])

np.intersect1d(a,b)

In [ ]:
#remove from array those that exist in another
np.setdiff1d(a,b)

In [ ]:
#swap two columns in 2d array
swap2d = np.arange(9).reshape(3,3)
swap2d

In [ ]:
swap2d[:,[0,2,1]]

In [ ]:
#reverse
swap2d[::-1]

In [ ]:
swap2d

In [ ]:
swap2d[:,::-1]

In [ ]:
#find max in 2d array 
swap2d

In [ ]:
#axis=1 is rows
np.amax(swap2d,axis=1)

In [ ]:
np.amax(swap2d)

In [ ]:
#axis=0 is columns
np.amax(swap2d,axis=0)

In [ ]:
#drop missing values
bad_Data = np.array([1,2,3,np.nan,5,np.nan,7,np.nan])
bad_Data

In [ ]:
bad_Data[np.isnan(bad_Data)]

In [ ]:
bad_Data[~np.isnan(bad_Data)]

In [ ]:
bad_Data[!np.isnan(bad_Data)]